version: '3.3'
services:
  app:
    container_name: app
    image: php:7.4-cli
    working_dir: /app
    volumes:
      - ./:/app
      - ./vendor:/app/vendor:cached
    ports:
      - 80:80
    tty: true
    env_file:
      - .env

  database:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_DATABASE: "clean_architecture"
    volumes:
      - "./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d"
    ports:
      - 3306:3306
